var musicListLv15 = [
	["INDEPENDENT SKY","GRV","15"],
	["Opium and Purple haze","GRV","15"],
	["夏色DIARY -Summer Dazzlin' Vacation miX-","GRV","15"],
	["2 MINUTES FIGHTERS","EXH","15"],
	["ΑΩ","EXH","15"],
	["AYAKASHI","EXH","15"],
	["BEAT-NEW-WORLD","EXH","15"],
	["Blastix Riotz","EXH","15"],
	["Borealis","EXH","15"],
	["Chant du Cygne","EXH","15"],
	["CRITICAL LINE","EXH","15"],
	["Discloze","EXH","15"],
	["EBONY & IVORY","EXH","15"],
	["ΕΛΠΙΣ","EXH","15"],
	["Everlasting Message","EXH","15"],
	["F.K.S.","EXH","15"],
	["False Cross","EXH","15"],
	["FIRE FIRE(Kazmasa Remix)","EXH","15"],
	["Firestorm","EXH","15"],
	["gigadelic(m3rkAb4# R3m!x)","EXH","15"],
	["gigadelic (かめりあ's ''The TERA'' RMX)","EXH","15"],
	["Happy Sensation","EXH","15"],
	["HAVOX","EXH","15"],
	["Hyper☆Chipspace","EXH","15"],
	["INF-B《L-aste-R》","EXH","15"],
	["Innocent Floor","EXH","15"],
	["Invitation from Mr.C","EXH","15"],
	["KAC 2012 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX-","EXH","15"],
	["LegenD.","EXH","15"],
	["NEON WORLD","EXH","15"],
	["Opium and Purple haze","EXH","15"],
	["Ops:Code-Rapture-","EXH","15"],
	["Pon-Pon-Pompoko Dai-Sen-Saw!","EXH","15"],
	["Preserved Valkyria","EXH","15"],
	["Pure Evil (Kobaryo FTN-Remix)","EXH","15"],
	["Rubeus","EXH","15"],
	["Sayonara Planet Wars","EXH","15"],
	["Scarlet Pinheel","EXH","15"],
	["Shanghai Wu Long ～上海舞龍～","EXH","15"],
	["Sounds Of Summer","EXH","15"],
	["The Sampling Paradise (P*Light Remix)","EXH","15"],
	["THUNDERCRACK","EXH","15"],
	["TIEFSEE","EXH","15"],
	["TOXIC VIBRATION","EXH","15"],
	["tricky trick","EXH","15"],
	["Twin Rocket","EXH","15"],
	["UnivEarth","EXH","15"],
	["Vampire's Territory","EXH","15"],
	["veRtrageS","EXH","15"],
	["Warriors Aboot","EXH","15"],
	["Witch in Sweetsland","EXH","15"],
	["World's end","EXH","15"],
	["XyHATTE","EXH","15"],
	["あれこれそれどれ","EXH","15"],
	["イグジスタンス","EXH","15"],
	["きらきらタイム☆","EXH","15"],
	["ネメシス SDVX Edit","EXH","15"],
	["パ→ピ→プ→Yeah!","EXH","15"],
	["ほおずき程度には赤い頭髪","EXH","15"],
	["ぼくらしかしらない","EXH","15"],
	["鬼天","EXH","15"],
	["感情の魔天楼 ～ Arr.Demetori","EXH","15"],
	["紅の剣舞","EXH","15"],
	["混乱少女♥そふらんちゃん!!","EXH","15"],
	["幸せになれる隠しコマンドがあるらしい","EXH","15"],
	["灼熱Beach Side Bunny","EXH","15"],
	["消失","EXH","15"],
	["到達してしまった僕らと夢と希望の最之果","EXH","15"],
	["夏色DIARY -Summer Dazzlin' Vacation miX-","EXH","15"],
	["暴走","EXH","15"],
	["無気力クーデター","EXH","15"],
	["無双","EXH","15"],
	["物凄い狂っとるフランちゃんが物凄いうた","EXH","15"],
	["量子の海のリントヴルム","EXH","15"],
	["Crack Traxxxx","GRV","15"],
	["Dawn of Asia","GRV","15"],
	["Double Universe","GRV","15"],
	["INFINITY OVERDRIVE","GRV","15"],
	["少年は空を辿る Prog Piano Remix","GRV","15"],
	["Cleopatrysm","INF","15"],
	["御千手メディテーション","INF","15"],
	["患部で止まってすぐ溶ける ～ 狂気の優曇華院","INF","15"],
	["打打打打打打打打打打","INF","15"],
	["BabeL ～Next Story～","EXH","15"],
	["Black Emperor","EXH","15"],
	["BLACK or WHITE?","EXH","15"],
	["Booths of Fighters","EXH","15"],
	["Brain Power","EXH","15"],
	["C18H27NO3","EXH","15"],
	["choux à la crème","EXH","15"],
	["CODE -CRiMSON-","EXH","15"],
	["Crack Traxxxx","EXH","15"],
	["DEADLOCK XXX","EXH","15"],
	["Decretum","EXH","15"],
	["Dignity","EXH","15"],
	["#FairyJoke #SDVX_Edit","EXH","15"],
	["Fiat Lux","EXH","15"],
	["FIRE FIRE -DARK BLAZE REMIX-","EXH","15"],
	["FLYING OUT TO THE SKY","EXH","15"],
	["gigadelic -stance xxxx-","EXH","15"],
	["Growth Memories","EXH","15"],
	["HAELEQUIN","EXH","15"],
	["Harpuia","EXH","15"],
	["Hellfire","EXH","15"],
	["HYENA","EXH","15"],
	["Idola","EXH","15"],
	["Innocent Tempest","EXH","15"],
	["INSECTICIDE","EXH","15"],
	["IX","EXH","15"],
	["Joyeuse","EXH","15"],
	["KHAMEN BREAK","EXH","15"],
	["KiLLeR MeRMaiD","EXH","15"],
	["Last Concerto","EXH","15"],
	["Little princess has no identity.","EXH","15"],
	["Lunartic Dial","EXH","15"],
	["Mist In Hell","EXH","15"],
	["Our Faith (Faithful MTL Remix)","EXH","15"],
	["Pure Evil","EXH","15"],
	["Pure Evil-Aya2g Drm'n Tech Rmx-","EXH","15"],
	["Qubism","EXH","15"],
	["Quietus Ray","EXH","15"],
	["Sakura Mirage","EXH","15"],
	["snow storm -euphoria-","EXH","15"],
	["Starlight Express","EXH","15"],
	["True Blue","EXH","15"],
	["U.N.オーエンは彼女なのか？haru_naba Remix","EXH","15"],
	["U.N.オーエンは彼女なのか？(TO-HOlic mix)","EXH","15"],
	["VALLIS-NERIA","EXH","15"],
	["Verse IV","EXH","15"],
	["VILE CAT","EXH","15"],
	["werewolf howls.","EXH","15"],
	["Wish upon Twin Stars","EXH","15"],
	["XROSS INFECTION","EXH","15"],
	["イゴモヨス＝オムルのテーマによるブヨブヨ・スケッチの試み","EXH","15"],
	["コンベア速度Max!? しゃいにん☆廻転ズシ''Sushi&Peace''","EXH","15"],
	["デストロイマーチ","EXH","15"],
	["バンブーソード・ガール","EXH","15"],
	["ボルテ体操第一","EXH","15"],
	["ムーニャポヨポヨスッポコニャーゴ","EXH","15"],
	["ラクガキスト","EXH","15"],
	["朱と碧のランページ","EXH","15"],
	["悪性ロリィタマキャヴェリズム","EXH","15"],
	["音楽 -resolve-","EXH","15"],
	["音楽 -壊音楽 mix-","EXH","15"],
	["最終鬼畜妹フランドール・S","EXH","15"],
	["少女暴動","EXH","15"],
	["信仰は儚き人間の為に ～ Arr.Demetori","EXH","15"],
	["超越してしまった彼女と其を生み落した理由","EXH","15"],
	["轟け！恋のビーンボール！！","EXH","15"],
	["柳の下のデュラハン hard chaos mix","EXH","15"],
	["Absurd Gaff","GRV","15"],
	["éclair au chocolat","GRV","15"],
	["EGG","GRV","15"],
	["freaky freak","GRV","15"],
	["PANIC HOLIC","GRV","15"],
	["TRIGGER★HAPPY","GRV","15"],
	["World Vertex","GRV","15"],
	["Xepher Light and Darkness Dragon Remix","GRV","15"],
	["カミサマネジマキ","GRV","15"],
	["香港功夫大旋風","GRV","15"],
	["AA BlackY mix","INF","15"],
	["ALBIDA Powerless Mix","INF","15"],
	["croiX","INF","15"],
	["Distorted Floor","INF","15"],
	["Dynasty","INF","15"],
	["FLOWER REDALiCE Remix","INF","15"],
	["Ganymede kamome mix","INF","15"],
	["good high school","INF","15"],
	["Gott","INF","15"],
	["Nyan Cat","INF","15"],
	["TYCOON","INF","15"],
	["ナイト・オブ・ナイツ","INF","15"],
	["天ノ弱","INF","15"],
	["過食性:アイドル症候群","INF","15"],
	["「月風魔伝」龍骨鬼戦 yks Remix","INF","15"],
	["冥 Rockin' SWING REMIX","INF","15"],
	["AA BlackY mix","EXH","15"],
	["Absurd Gaff","EXH","15"],
	["croiX","EXH","15"],
	["Dynasty","EXH","15"],
	["FLOWER REDALiCE Remix","EXH","15"],
	["Ganymede kamome mix","EXH","15"],
	["Gott","EXH","15"],
	["Max Burning!!","EXH","15"],
	["Onigo","EXH","15"],
	["PANIC HOLIC","EXH","15"],
	["The world of sound","EXH","15"],
	["V.I.P.","EXH","15"],
	["金縛りの逢を","EXH","15"],
	["大宇宙ステージ","EXH","15"],
	["香港功夫大旋風","EXH","15"],
	["冥 Rockin' SWING REMIX","EXH","15"]
];

var musicListLv16 = [
	["ΑΩ","EXH","16"],
	["Blastix Riotz","EXH","16"],
	["Everlasting Message","EXH","16"],
	["KAC 2012 ULTIMATE MEDLEY -HISTORIA SOUND VOLTEX-","EXH","16"],
	["Preserved Valkyria","EXH","16"],
	["XyHATTE","EXH","16"],
	["XROSS INFECTION","EXH","16"],
	["Bangin' Burst","EXH","16"],
	["For UltraPlayers","EXH","16"],
	["大宇宙ステージ","EXH","16"],
	["Max Burning!!","EXH","16"]
];